# Generated by Django 4.2.1 on 2023-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=228)),
                ("image", models.ImageField(upload_to="dash_board/")),
                ("text", models.TextField()),
            ],
        ),
    ]
